#!/bin/bash

# Empty AWS staging bucket
aws s3 rm s3://my.kabbalah.com --recursive

# Copy relevant files to staging bucket
aws s3 sync build/ s3://my.kabbalah.com/ --exclude "Guardfile"

# Display content of bucket
aws s3 ls s3://my.kabbalah.com
